language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
- pip install coverage
- pip install coveralls
script:
 - cd test
 - env PYTHONPATH=.. python -m unittest --verbose all
 - cd ..
after_success:
- coveralls
