environment:
    matrix:
        - PYTHON: "C:\\Python26"
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python26-x64"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37-x64"

install:
    - "python --version"
    - "python -m pip install --upgrade pip"
    - "python -m pip install coverage coveralls wheel"

build_script:
    - "%CMD_IN_ENV% python setup.py build"

test_script:
    - "cd test"
    - "%PYTHON%\\python.exe -m unittest --verbose all"
    - "coverage run test\\all.py"

after_test:
    - "coveralls"
    - "%CMD_IN_ENV% python setup.py bdist_wheel"

artifacts:
    - path: dist\*

#on_success:
# upload artifacts
